[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wasm-bindgen = "0.2.93"

[lib]
crate-type = [
  "cdylib",
] # This tells Rust to compile into a C-compatible dynamic library (WASM)

[package.metadata.wasm-pack.profile.release]
wasm-opt = false # Disable wasm-opt for faster builds during development
