[package]
name = "cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
ctor = "0.2.8"
tokio = { version = "1.40.0", features = ["full"] }
workerpool = { path = "../workerpool" }
workerpool-macro = { path = "../workerpool-macro" }
