[package]
name = "cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
ctor = "0.2.8"
workerpool = { path = "../workerpool" }
workerpool-macro = { path = "../workerpool-macro" }
